language: node_js
sudo: false
node_js:
- 8
install:
- npm install -f
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: B6jr30rVWx9R+w2Lsyt48A/oYT7qu0G4doHZWckZw7tqjcY/ISEFhLdb+EhFJwqq4rCpBijE39C4cm3LXojXnFc0FZLz/n/6e7z4obdk+eBn695g5a1XgL4BsMKV9ANnuLW7psJiSga2Kfr+zr7xYmYaoHnXggo/04CM5RKHynFemlUvmPm2mbzmoJBkwu4MZ9DVMKsJAAKSHKpiz/VWAinlkXNPeIU7o/tDoHvMxrayf6xU6Ox1aF51/7mMbPWYqbFF136yvp9AQrnta9MFJkzAyGHBF01ZqEAPMokydsZ6+qmrwIUjV8IPNxPnxQEHcNNQPnFGh+47gnFFr/bk9M4kNvikbBQDAWrcTnnpxKbRGdKx2vwz2sJ++OgS9hGG3A78h48SRtC8cq5OAztObE0alRZlVDiHubUoRJlry+kIXCxrxzf6dnijmHEVNWG0t8TZGmGel9uF/GaY29U0VcVrBf4PT+Hxx5JiLKQbs7Nudmrs7EM78iZ7vllahc+1yVJ1xQbMbT+u8H8HRZokYUdqP4wFmgedjU2m+8xsn10hyUPahEnyrqBjul79ca0WpIFCHGGEeVbKqGhCznVHcjmSFy2vhDk/ryF+ILylJMW3Z+vE7RhviDjrNeiKXUaF7E77Md+7NQtHjqWWmxokdwzgIfOfMshuGk9c6X+7uJI=
  app: pressy-dev
  on:
    repo: dogganidhal/pressy-core
    branch: develop
