# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST https://api.heroku.com/apps/pressy-dev/builds
Accept: application/vnd.heroku+json; version=3
Content-Type: application/json
Authorization: Basic ZG9nZ2EubmlkaGFsQGdtYWlsLmNvbTpBNjhmNzNuOTZA

{
  "source_blob": {
    "url": "https://codeload.github.com/dogganidhal/pressy/legacy.tar.gz/d2115a85fc398118a51ba518932505bd676e24fb?token=AWYnfqbV93pfXwcjPVbOXSVRXPmlTFfAks5bpH5PwA=="
  }
}

###

GET https://api.heroku.com/apps/pressy-dev/builds
Accept: application/vnd.heroku+json; version=3
Content-Type: application/json
Authorization: Basic ZG9nZ2EubmlkaGFsQGdtYWlsLmNvbTpBNjhmNzNuOTZA

###