version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/node:10.0.0 # ...with this image as the primary container; this is where all `steps` will run
      - image: node:10.0.0 # for the Docker Library image
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: npm test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Mobile API to Heroku
          command: |
            git push https://heroku:04843c0f-09ac-4737-a369-d015e5fe617b@git.heroku.com/pressy-mobile-api-dev.git develop:master
      - run:
          name: Deploy Admin API to Heroku
          command: |
            git push https://heroku:04843c0f-09ac-4737-a369-d015e5fe617b@git.heroku.com/pressy-admin-api-dev.git develop:master
      - run:
          name: Deploy Driver API to Heroku
          command: |
            git push https://heroku:04843c0f-09ac-4737-a369-d015e5fe617b@git.heroku.com/pressy-driver-api-dev.git develop:master
      - run:
          name: Deploy Laundry API to Heroku
          command: |
            git push https://heroku:04843c0f-09ac-4737-a369-d015e5fe617b@git.heroku.com/pressy-laundry-api-dev.git develop:master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
              - master
              - develop